apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod

spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "Hello from First Pod" >> /data/message.txt
          echo "Current file contents:"
          cat /data/message.txt
          sleep 3600
      volumeMounts:
        - name: storage
          mountPath: /data

  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc
