apiVersion: v1
kind: Secret
metadata:
  name: my-secrets
  namespace: capstone

type: Opaque

stringData:
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev@123
  MYSQL_ROOT_PASSWORD: s3cureP@ssw0rd
  MYSQL_DATABASE: mydatabase
