apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  labels: 
    app: resource-demo

spec:
  containers:
  - name: resource-demo
    image: nginx:latest
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi" 

